/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DownloadAppRouteImport } from './routes/download-app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SessionSessionIdRouteImport } from './routes/session/$sessionId'
import { Route as AdminAcademicProgramsRouteImport } from './routes/admin/academic/programs'
import { Route as AdminAcademicSubjectsRouteImport } from './routes/admin/academic/subjects'
import { Route as AdminCampusIndexRouteImport } from './routes/admin/campus/index'
import { Route as AdminTimetableIndexRouteImport } from './routes/admin/timetable/index'
import { Route as AdminTimetableImportRouteImport } from './routes/admin/timetable/import'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminUsersImportRouteImport } from './routes/admin/users/import'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadAppRoute = DownloadAppRouteImport.update({
  id: '/download-app',
  path: '/download-app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcademicProgramsRoute = AdminAcademicProgramsRouteImport.update({
  id: '/academic/programs',
  path: '/academic/programs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicSubjectsRoute = AdminAcademicSubjectsRouteImport.update({
  id: '/academic/subjects',
  path: '/academic/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampusIndexRoute = AdminCampusIndexRouteImport.update({
  id: '/campus/',
  path: '/campus/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetableIndexRoute = AdminTimetableIndexRouteImport.update({
  id: '/timetable/',
  path: '/timetable/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimetableImportRoute = AdminTimetableImportRouteImport.update({
  id: '/timetable/import',
  path: '/timetable/import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersImportRoute = AdminUsersImportRouteImport.update({
  id: '/users/import',
  path: '/users/import',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/download-app': typeof DownloadAppRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/academic/programs': typeof AdminAcademicProgramsRoute
  '/admin/academic/subjects': typeof AdminAcademicSubjectsRoute
  '/admin/timetable/import': typeof AdminTimetableImportRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/import': typeof AdminUsersImportRoute
  '/admin/campus/': typeof AdminCampusIndexRoute
  '/admin/timetable/': typeof AdminTimetableIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/download-app': typeof DownloadAppRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/academic/programs': typeof AdminAcademicProgramsRoute
  '/admin/academic/subjects': typeof AdminAcademicSubjectsRoute
  '/admin/timetable/import': typeof AdminTimetableImportRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/import': typeof AdminUsersImportRoute
  '/admin/campus': typeof AdminCampusIndexRoute
  '/admin/timetable': typeof AdminTimetableIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/download-app': typeof DownloadAppRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/academic/programs': typeof AdminAcademicProgramsRoute
  '/admin/academic/subjects': typeof AdminAcademicSubjectsRoute
  '/admin/timetable/import': typeof AdminTimetableImportRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/users/import': typeof AdminUsersImportRoute
  '/admin/campus/': typeof AdminCampusIndexRoute
  '/admin/timetable/': typeof AdminTimetableIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/download-app'
    | '/login'
    | '/reset-password'
    | '/session/$sessionId'
    | '/admin/'
    | '/admin/academic/programs'
    | '/admin/academic/subjects'
    | '/admin/timetable/import'
    | '/admin/users/$userId'
    | '/admin/users/import'
    | '/admin/campus/'
    | '/admin/timetable/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/download-app'
    | '/login'
    | '/reset-password'
    | '/session/$sessionId'
    | '/admin'
    | '/admin/academic/programs'
    | '/admin/academic/subjects'
    | '/admin/timetable/import'
    | '/admin/users/$userId'
    | '/admin/users/import'
    | '/admin/campus'
    | '/admin/timetable'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/download-app'
    | '/login'
    | '/reset-password'
    | '/session/$sessionId'
    | '/admin/'
    | '/admin/academic/programs'
    | '/admin/academic/subjects'
    | '/admin/timetable/import'
    | '/admin/users/$userId'
    | '/admin/users/import'
    | '/admin/campus/'
    | '/admin/timetable/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DownloadAppRoute: typeof DownloadAppRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download-app': {
      id: '/download-app'
      path: '/download-app'
      fullPath: '/download-app'
      preLoaderRoute: typeof DownloadAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/academic/programs': {
      id: '/admin/academic/programs'
      path: '/academic/programs'
      fullPath: '/admin/academic/programs'
      preLoaderRoute: typeof AdminAcademicProgramsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academic/subjects': {
      id: '/admin/academic/subjects'
      path: '/academic/subjects'
      fullPath: '/admin/academic/subjects'
      preLoaderRoute: typeof AdminAcademicSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campus/': {
      id: '/admin/campus/'
      path: '/campus'
      fullPath: '/admin/campus/'
      preLoaderRoute: typeof AdminCampusIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetable/': {
      id: '/admin/timetable/'
      path: '/timetable'
      fullPath: '/admin/timetable/'
      preLoaderRoute: typeof AdminTimetableIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timetable/import': {
      id: '/admin/timetable/import'
      path: '/timetable/import'
      fullPath: '/admin/timetable/import'
      preLoaderRoute: typeof AdminTimetableImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/import': {
      id: '/admin/users/import'
      path: '/users/import'
      fullPath: '/admin/users/import'
      preLoaderRoute: typeof AdminUsersImportRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAcademicProgramsRoute: typeof AdminAcademicProgramsRoute
  AdminAcademicSubjectsRoute: typeof AdminAcademicSubjectsRoute
  AdminTimetableImportRoute: typeof AdminTimetableImportRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersImportRoute: typeof AdminUsersImportRoute
  AdminCampusIndexRoute: typeof AdminCampusIndexRoute
  AdminTimetableIndexRoute: typeof AdminTimetableIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAcademicProgramsRoute: AdminAcademicProgramsRoute,
  AdminAcademicSubjectsRoute: AdminAcademicSubjectsRoute,
  AdminTimetableImportRoute: AdminTimetableImportRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersImportRoute: AdminUsersImportRoute,
  AdminCampusIndexRoute: AdminCampusIndexRoute,
  AdminTimetableIndexRoute: AdminTimetableIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DownloadAppRoute: DownloadAppRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
