name: secured_attendance

services:
  postgres:
    image: postgres
    container_name: secured_attendance-postgres
    environment:
      POSTGRES_DB: secured_attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - secured_attendance_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  secured_attendance_postgres_data:
